# When editing this file, remember that http://www.yamllint.com is your friend :-)
---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      image: centos:7.2.1511
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      forward:
      - 80:80
      - 8080:8080
      - 443:443

suites:
  - name: default
    run_list:
      - recipe[aps::default]
      - recipe[alfresco-utils::node_json]
    verifier:
      inspec_tests:
        - name: chef-aps-inspec-tomcat
          git: https://github.com/Alfresco/chef-aps-inspec-tomcat
          branch: 'TAA-960'
        - path: test/inspec/

    attributes: {
      "aps-core" : {
        "version" : "1.6.0",
        "nexus" : {
          "username" : "<%= ENV['NEXUS_USERNAME'] %>",
          "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
        }
      }
    }
