---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.23"}]

    driver:
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box


suites:
  - name: default
    run_list:
      - recipe[aps::default]
      - recipe[alfresco-utils::node_json]
    verifier:
      inspec_tests:
        - name: chef-aps-inspec-tomcat
          git: https://github.com/Alfresco/chef-aps-inspec-tomcat
          branch: 'TAA-960'
        - path: test/inspec/
    attributes: {
      "aps-core" : {
        "version" : "1.6.0",
        "nexus" : {
          "username" : "<%= ENV['NEXUS_USERNAME'] %>",
          "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
        }
      }
    }
