---
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12.19.36
verifier:
  name: inspec
platforms:
- name: centos-7
  driver_config:
    image: centos:7.2.1511
    platform: centos
    run_command: "/usr/sbin/init"
    privileged: true
    forward:
    - 80:80
    - 8080:8080
    - 443:443
suites:
- name: aps-mysql
  run_list:
  - recipe[aps::default]
  - recipe[alfresco-utils::node_json]
  verifier:
    inspec_tests:
    - name: chef-aps-inspec-tomcat
      git: https://github.com/Alfresco/chef-aps-inspec-tomcat
    - name: chef-aps-inspec-mysql
      git: https://github.com/Alfresco/chef-aps-inspec-mysql
    - name: chef-aps-inspec
      path: test/inspec
  attributes:
    aps-core:
      version: 1.6.0
      nexus:
        username: "<%= ENV['NEXUS_USERNAME'] %>"
        password: "<%= ENV['NEXUS_PASSWORD'] %>"
    aps-db:
      engine: mysql
- name: aps-postgres
  run_list:
  - recipe[aps::default]
  - recipe[alfresco-utils::node_json]
  verifier:
    inspec_tests:
    - name: chef-aps-inspec-tomcat
      git: https://github.com/Alfresco/chef-aps-inspec-tomcat
    - name: chef-aps-inspec-postgres
      git: https://github.com/Alfresco/chef-aps-inspec-postgres
    - name: chef-aps-inspec
      path: test/inspec
  attributes:
    aps-core:
      version: 1.6.0
      nexus:
        username: "<%= ENV['NEXUS_USERNAME'] %>"
        password: "<%= ENV['NEXUS_PASSWORD'] %>"
    aps-db:
      engine: postgres
