---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.23"}]

    driver:
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box


suites:
  - name: aps-mysql
    run_list:
      - recipe[aps::default]
      - recipe[alfresco-utils::node_json]
    verifier:
      inspec_tests:
        - name: chef-aps-inspec-tomcat
          git: https://github.com/Alfresco/chef-aps-inspec-tomcat
        - name: chef-aps-inspec-mysql
          git: https://github.com/Alfresco/chef-aps-inspec-mysql
        - name: chef-aps-inspec-core
          git: https://github.com/Alfresco/chef-aps-inspec-core
        - name: chef-aps-inspec
          path: test/inspec
    attributes: {
      "aps-core" : {
        "version" : "1.6.0",
        "nexus" : {
          "username" : "<%= ENV['NEXUS_USERNAME'] %>",
          "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
        }
      },
      "aps" : {
          "db" : {
            "engine" : "mysql"
          }
        }
     }
  - name: aps-postgres
    run_list:
      - recipe[aps::default]
      - recipe[alfresco-utils::node_json]
    verifier:
      inspec_tests:
        - name: chef-aps-inspec-tomcat
          git: https://github.com/Alfresco/chef-aps-inspec-tomcat
        - name: chef-aps-inspec-postgres
          git: https://github.com/Alfresco/chef-aps-inspec-postgres
        - name: chef-aps-inspec-core
          git: https://github.com/Alfresco/chef-aps-inspec-core
        - name: chef-aps-inspec
          path: test/inspec
    attributes: {
      "aps-core" : {
        "version" : "1.6.0",
        "nexus" : {
          "username" : "<%= ENV['NEXUS_USERNAME'] %>",
          "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
        },
        "activiti-app-properties" : {
          "datasource.driver" : "org.postgresql.Driver",
          "datasource.url" : "jdbc:postgresql://localhost:5432/process?characterEncoding=UTF-8",
          "hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect"
          }
      },
      "aps" : {
          "db" : {
            "engine" : "postgres"
          }
        }
     }
