name 'chef-aps'
maintainer 'Alfresco T&A Team'
maintainer_email 'devops@alfresco.com'
license 'Apache 2.0'
description 'Installs/Configures chef-aps'
long_description 'Installs/Configures chef-aps'
version '0.1.0'

depends 'aps-proxy'
depends 'aps-db'
depends 'aps-core'
depends 'aps-appserver'
depends 'apache_tomcat'
depends 'poise-derived', '~> 1.0.0'
depends 'alfresco-utils', '~> 1.1.0'
